# -*- coding: utf-8 -*-
"""Full_Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGQQ_mxvMN-inRDXncd8DCVhCCZjjZR-

# **HackBio_StageOne**

Write a python function for translating DNA to protein


Write a python function for calculating the hamming distance between your slack username (e.g josoga) and twitter/X (joseph) handle (synthesize one if you don’t have one). Feel free to pad it with extra words if they are not of the same length.
"""

# ============================================================
# HackBio Team Histidine – Stage One Task
# Author: Saumi Shah
# GitHub: https://github.com/saumisaurin-shah
# LinkedIn: https://www.linkedin.com/in/saumisaurin-shah/
# ============================================================

# --------------------------
# STANDARD DNA CODON TABLE
# --------------------------
CODON_TABLE = {
    "TTT":"F","TTC":"F","TTA":"L","TTG":"L","CTT":"L","CTC":"L","CTA":"L","CTG":"L",
    "ATT":"I","ATC":"I","ATA":"I",
    "ATG":"M",
    "GTT":"V","GTC":"V","GTA":"V","GTG":"V",
    "TCT":"S","TCC":"S","TCA":"S","TCG":"S","AGT":"S","AGC":"S",
    "CCT":"P","CCC":"P","CCA":"P","CCG":"P",
    "ACT":"T","ACC":"T","ACA":"T","ACG":"T",
    "GCT":"A","GCC":"A","GCA":"A","GCG":"A",
    "TAT":"Y","TAC":"Y",
    "CAT":"H","CAC":"H",
    "CAA":"Q","CAG":"Q",
    "AAT":"N","AAC":"N",
    "AAA":"K","AAG":"K",
    "GAT":"D","GAC":"D",
    "GAA":"E","GAG":"E",
    "TGT":"C","TGC":"C",
    "TGG":"W",
    "CGT":"R","CGC":"R","CGA":"R","CGG":"R","AGA":"R","AGG":"R",
    "GGT":"G","GGC":"G","GGA":"G","GGG":"G",
    "TAA":"*","TAG":"*","TGA":"*"
}

# ============================================================
# FUNCTION 1: TRANSLATE DNA → PROTEIN
# ============================================================
def translate_dna_to_protein(dna_seq, frame=0, stop_at_stop=True):
    seq = dna_seq.upper().replace(" ", "").replace("\n", "")
    protein = []

    for i in range(frame, len(seq) - 2, 3):
        codon = seq[i:i+3]
        aa = CODON_TABLE.get(codon, "X")  # Unknown codons become 'X'

        if aa == "*":  # Stop codon
            if stop_at_stop:
                break
            protein.append("*")
        else:
            protein.append(aa)

    return "".join(protein)

# ============================================================
# FUNCTION 2: HAMMING DISTANCE
# ============================================================
def calculate_hamming_distance(str1, str2, pad_char="_"):
    max_len = max(len(str1), len(str2))
    str1 = str1.ljust(max_len, pad_char)
    str2 = str2.ljust(max_len, pad_char)

    return sum(c1 != c2 for c1, c2 in zip(str1, str2))

# ============================================================
# BASIC UNIT TESTS
# ============================================================
def test_translation():
    assert translate_dna_to_protein("ATGAAA") == "MK"
    assert translate_dna_to_protein("ATGTAATTT") == "M"
    assert translate_dna_to_protein("ATGNNA") == "MX"
    print("DNA Translation Tests Passed ✓")

def test_hamming():
    assert calculate_hamming_distance("abc", "abc") == 0
    assert calculate_hamming_distance("abc", "axc") == 1
    assert calculate_hamming_distance("abc", "abcd") == 1
    assert calculate_hamming_distance("", "") == 0
    print("Hamming Distance Tests Passed ✓")

test_translation()
test_hamming()

# ============================================================
# EXAMPLE USAGE
# ============================================================
dna_example = "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"
protein_result = translate_dna_to_protein(dna_example)

slack = "saumi_shah"
twitter = "Saumi@99"
hamming_result = calculate_hamming_distance(slack, twitter)

# ============================================================
# FINAL FORMATTED OUTPUT
# ============================================================
print("\n========== FINAL OUTPUT ==========")

print("\n--- DNA → Protein Translation ---")
print(f"Input DNA Sequence: {dna_example}")
print(f"Translated Protein: {protein_result}")

print("\n--- Hamming Distance Calculation ---")
print(f"Slack Username : {slack}")
print(f"Twitter Handle : {twitter}")
print(f"Hamming Distance: {hamming_result}")

print("\n===================================")