# -*- coding: utf-8 -*-
"""HacbBio_SupriseTask

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eywRLEAK-5zkm384oXqmehKob-yTAjxH
"""

#Surprise Task

# PART A - Gene Expression Analysis
# 1A–1F: Reproducing all plots in a 3x3 grid

# -----------------------------
# Step 0: Imports
# -----------------------------
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# -----------------------------
# Step 1: Load Datasets
# -----------------------------
# 1A: Normalized counts for heatmap
norm_counts_url = "https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/Python/Dataset/hbr_uhr_top_deg_normalized_counts.csv"
df_norm = pd.read_csv(norm_counts_url, index_col=0)
df_norm = df_norm.select_dtypes(include=np.number)  # Only numeric

# 1B: DEG results for volcano plot
deg_url = "https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/Python/Dataset/hbr_uhr_deg_chr22_with_significance.csv"
df_deg = pd.read_csv(deg_url)
df_deg.columns = df_deg.columns.str.strip()  # Cleaning column names
color_map = {'up':'green', 'down':'blue', 'ns':'orange'}
# PART B: Breast Cancer Data
bc_url = "https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/Python/Dataset/data-3.csv"
df_bc = pd.read_csv(bc_url)
features = ['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean']
df_bc = df_bc.dropna(subset=features)  # Removes missing values

# -----------------------------
# Step 2: Create 3x3 subplot grid
# -----------------------------
fig, axes = plt.subplots(3,3, figsize=(20,15))
axes = axes.flatten()

# -----------------------------
# 1A: Heatmap of Top DEGs
# -----------------------------
sns.heatmap(df_norm, cmap="Blues", ax=axes[0])
axes[0].set_title("1A: Heatmap of Top DEGs")

# -----------------------------
# 1B: Volcano Plot
# -----------------------------
sns.scatterplot(
    x="log2FoldChange",
    y="-log10PAdj",
    hue="significance",
    data=df_deg,
    palette=color_map,
    ax=axes[1]
)
axes[1].axvline(x=1, linestyle='--', color='grey')
axes[1].axvline(x=-1, linestyle='--', color='grey')
axes[1].set_xlabel("log2(Fold Change)")
axes[1].set_ylabel("-log10(PAdj)")
axes[1].set_title("1B: Volcano Plot")
axes[1].legend(title="Significance")

# -----------------------------
# 1C: Scatter Plot (radius_mean vs texture_mean)
# -----------------------------
sns.scatterplot(
    x="radius_mean",
    y="texture_mean",
    hue="diagnosis",
    data=df_bc,
    palette={'M':'blue','B':'orange'},
    ax=axes[2]
)
axes[2].set_title("1C: Radius vs Texture")

# -----------------------------
# 1D: Correlation Heatmap
# -----------------------------
sns.heatmap(df_bc[features].corr(), annot=True, cmap="Blues", ax=axes[3])
axes[3].set_title("1D: Correlation Heatmap")

# -----------------------------
# 1E: Scatter Plot (smoothness_mean vs compactness_mean)
# -----------------------------
sns.scatterplot(
    x="smoothness_mean",
    y="compactness_mean",
    hue="diagnosis",
    data=df_bc,
    palette={'M':'blue','B':'orange'},
    ax=axes[4]
)
axes[4].set_title("1E: Smoothness vs Compactness")
axes[4].grid(True)

# -----------------------------
# 1F: Density Plot (area_mean by diagnosis)
# -----------------------------
sns.kdeplot(df_bc[df_bc['diagnosis']=='M']['area_mean'], fill=True, color='blue', bw_adjust=0.5, ax=axes[5], label='M')
sns.kdeplot(df_bc[df_bc['diagnosis']=='B']['area_mean'], fill=True, color='orange', bw_adjust=0.5, ax=axes[5], label='B')
axes[5].set_title("1F: Density of Area Mean by Diagnosis")
axes[5].set_xlabel("area_mean")
axes[5].set_ylabel("Density")
axes[5].legend()

# -----------------------------
# Hide empty subplots
# -----------------------------
for i in range(6,9):
    axes[i].axis('off')

plt.tight_layout()
plt.show()